#!/usr/bin/env python3
"""
Quick Start - Интерактивная настройка Reddit SaaS Validator
"""

import os
from colorama import init, Fore, Style

init(autoreset=True)

def print_header():
    """Печатает заголовок"""
    print(f"\n{Fore.CYAN}{'='*60}")
    print(f"{Fore.YELLOW}🚀 Reddit SaaS Validator - Quick Start{Style.RESET_ALL}")
    print(f"{Fore.CYAN}{'='*60}\n{Style.RESET_ALL}")

def print_section(title):
    """Печатает заголовок секции"""
    print(f"\n{Fore.CYAN}▶ {title}{Style.RESET_ALL}")
    print(f"{Fore.CYAN}{'-'*60}{Style.RESET_ALL}")

def get_input(prompt, required=True, default=None):
    """Получает input от пользователя"""
    if default:
        prompt_text = f"{Fore.WHITE}{prompt} {Fore.YELLOW}[{default}]{Fore.WHITE}: {Style.RESET_ALL}"
    else:
        prompt_text = f"{Fore.WHITE}{prompt}: {Style.RESET_ALL}"
    
    while True:
        value = input(prompt_text).strip()
        
        if not value and default:
            return default
        
        if not value and required:
            print(f"{Fore.RED}❌ Это поле обязательно!{Style.RESET_ALL}")
            continue
        
        if not value and not required:
            return ''
        
        return value

def setup_reddit():
    """Настройка Reddit credentials"""
    print_section("1️⃣  Reddit API")
    
    print(f"{Fore.YELLOW}ℹ️  Получите credentials:{Style.RESET_ALL}")
    print(f"   1. https://www.reddit.com/prefs/apps")
    print(f"   2. Create app → script")
    print(f"   3. Скопируйте client_id и client_secret\n")
    
    client_id = get_input("Reddit Client ID")
    client_secret = get_input("Reddit Client Secret")
    user_agent = get_input("Reddit User Agent", default="SaaS_Validator/1.0")
    
    return {
        'REDDIT_CLIENT_ID': client_id,
        'REDDIT_CLIENT_SECRET': client_secret,
        'REDDIT_USER_AGENT': user_agent
    }

def setup_twitter():
    """Настройка Twitter credentials"""
    print_section("2️⃣  Twitter/X API (опционально)")
    
    print(f"{Fore.YELLOW}ℹ️  Free tier: $0/месяц, 500k твитов{Style.RESET_ALL}")
    print(f"   1. https://developer.twitter.com/en/portal/dashboard")
    print(f"   2. Создайте приложение")
    print(f"   3. Keys and tokens → Generate Bearer Token\n")
    
    skip = input(f"{Fore.WHITE}Пропустить Twitter? (y/N): {Style.RESET_ALL}").strip().lower()
    
    if skip == 'y':
        return {}
    
    bearer_token = get_input("Twitter Bearer Token")
    
    return {'TWITTER_BEARER_TOKEN': bearer_token}

def setup_linkedin():
    """Настройка LinkedIn credentials"""
    print_section("3️⃣  LinkedIn (опционально)")
    
    print(f"{Fore.YELLOW}ℹ️  Используйте ваш обычный LinkedIn аккаунт{Style.RESET_ALL}")
    print(f"{Fore.RED}⚠️  LinkedIn может заблокировать за активный scraping!{Style.RESET_ALL}")
    print(f"   Рекомендации:")
    print(f"   - Делайте задержки 2-3 секунды")
    print(f"   - Не больше 50-100 запросов в день")
    print(f"   - Используйте VPN\n")
    
    skip = input(f"{Fore.WHITE}Пропустить LinkedIn? (y/N): {Style.RESET_ALL}").strip().lower()
    
    if skip == 'y':
        return {}
    
    email = get_input("LinkedIn Email")
    password = get_input("LinkedIn Password")
    
    return {
        'LINKEDIN_EMAIL': email,
        'LINKEDIN_PASSWORD': password
    }

def create_env_file(credentials):
    """Создаёт файл .env"""
    with open('.env', 'w') as f:
        f.write("# Reddit SaaS Validator - Credentials\n")
        f.write("# Generated by quick_start.py\n\n")
        
        # Reddit
        f.write("# Reddit API\n")
        for key, value in credentials['reddit'].items():
            f.write(f"{key}={value}\n")
        
        # Twitter
        if credentials.get('twitter'):
            f.write("\n# Twitter/X API\n")
            for key, value in credentials['twitter'].items():
                f.write(f"{key}={value}\n")
        
        # LinkedIn
        if credentials.get('linkedin'):
            f.write("\n# LinkedIn\n")
            for key, value in credentials['linkedin'].items():
                f.write(f"{key}={value}\n")

def main():
    """Главная функция"""
    print_header()
    
    print(f"{Fore.WHITE}Этот мастер поможет настроить доступ к API.{Style.RESET_ALL}")
    print(f"{Fore.WHITE}Минимум: Reddit (обязательно){Style.RESET_ALL}")
    print(f"{Fore.WHITE}Опционально: Twitter и LinkedIn для полного анализа\n{Style.RESET_ALL}")
    
    # Собираем credentials
    credentials = {}
    
    # Reddit (обязательно)
    credentials['reddit'] = setup_reddit()
    
    # Twitter (опционально)
    credentials['twitter'] = setup_twitter()
    
    # LinkedIn (опционально)
    credentials['linkedin'] = setup_linkedin()
    
    # Создаём .env файл
    print_section("💾 Сохранение настроек")
    create_env_file(credentials)
    
    print(f"\n{Fore.GREEN}✓ Файл .env создан!{Style.RESET_ALL}")
    
    # Итог
    platforms = ['Reddit']
    if credentials.get('twitter'):
        platforms.append('Twitter')
    if credentials.get('linkedin'):
        platforms.append('LinkedIn')
    
    print(f"\n{Fore.CYAN}{'='*60}{Style.RESET_ALL}")
    print(f"{Fore.GREEN}✓ Настройка завершена!{Style.RESET_ALL}")
    print(f"\n{Fore.CYAN}📊 Подключённые платформы:{Style.RESET_ALL} {', '.join(platforms)}")
    print(f"\n{Fore.YELLOW}Следующий шаг:{Style.RESET_ALL}")
    print(f"  {Fore.WHITE}python validator.py \"your SaaS idea\"{Style.RESET_ALL}")
    print(f"\n{Fore.CYAN}{'='*60}\n{Style.RESET_ALL}")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n{Fore.YELLOW}⚠️  Прервано пользователем{Style.RESET_ALL}")
        exit(0)
    except Exception as e:
        print(f"\n{Fore.RED}❌ Ошибка: {e}{Style.RESET_ALL}")
        exit(1)
